version: '3.8'
services:
  ifmthub-backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=test # Escolha o perfil desejado aqui: dev ou test
      - DATABASE_URL=jdbc:postgresql://host.docker.internal:5432/ifmthub?user=postgres&password=123456
      - SENDGRID_API_KEY=sendgrid_api_key # Chave do sendgrid
    ports:
      - "8080:8080"
